version: '3'

services:
  application.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  application.entities:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  application.data:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  application.common:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat



